#!/bin/bash

set -evx

# Needed to install Cypress plugins
npm install

# Start Cypress tests with docker
docker run -v $PWD:/workdir -w /workdir                     \
    -e CYPRESS_TAGS=$CYPRESS_TAGS                           \
    -e ELEMENTAL_UI_VERSION=$ELEMENTAL_UI_VERSION           \
    -e K8S_UPSTREAM_VERSION=$K8S_UPSTREAM_VERSION           \
    -e K8S_VERSION_TO_PROVISION=$K8S_VERSION_TO_PROVISION   \
    -e OPERATOR_REPO=$OPERATOR_REPO                         \
    -e PROXY=$PROXY                                         \
    -e QASE_TOKEN=$QASE_TOKEN                               \
    -e QASE_REPORT=1                                        \
    -e RANCHER_VERSION=$RANCHER_VERSION                     \
    -e RANCHER_PASSWORD=$RANCHER_PASSWORD                   \
    -e RANCHER_URL=$RANCHER_URL                             \
    -e RANCHER_USER=$RANCHER_USER                           \
    -e UI_ACCOUNT=$UI_ACCOUNT                               \
    -e UPGRADE_IMAGE=$UPGRADE_IMAGE                         \
    --add-host host.docker.internal:host-gateway            \
    --ipc=host                                              \
    $CYPRESS_DOCKER                                         \
    -s $SPEC